---
- name: Update apt cache
  apt: update_cache=yes

- name: Install Python
  apt: pkg=python3 state=present

- name: Install Python development packages
  apt: pkg=python3-dev state=present
  when: python_development | bool