---
- name: Ensure windshaft directory exists
  file: path="/opt/windshaft"
        owner={{ansible_ssh_user}}
        group={{ansible_ssh_user}}
        state=directory
  when: staging or production

- name: Synchronize Windshaft configuration
  synchronize: archive=no
               checksum=yes
               compress=no
               links=yes
               recursive=yes
               copy_links=no
               src="../../windshaft/"
               dest="/opt/windshaft"
  become: False
  when: staging or production
  notify:
    - Restart Windshaft

- name: Configure Windshaft systemd service definition
  template:
    src: windshaft.service.j2
    dest: /etc/systemd/system/windshaft.service
  notify:
    - Reload systemd
    - Restart Windshaft

- name: Ensure Windshaft application is running
  service: name=windshaft state=started

- name: Set up monit monitoring
  template: src=monit-windshaft.cfg.j2 dest=/etc/monit/conf.d/windshaft.cfg
  notify:
    - Restart monit
