app/scripts/filterbar/quality-controller.js
app/scripts/filterbar/label-formatter.js
app/scripts/filterbar/numeric-range-controller.js
app/scripts/filterbar/text-search-controller.js
app/scripts/filterbar/date-range-directive.js
app/scripts/filterbar/quality-directive.js
app/scripts/filterbar/filterbar-controller.js
app/scripts/filterbar/module.js
app/scripts/filterbar/filterbar-directive.js
app/scripts/filterbar/weather-controller.js
app/scripts/filterbar/options-controller.js
app/scripts/filterbar/text-search-directive.js
app/scripts/filterbar/options-directive.js
app/scripts/filterbar/weather-directive.js
app/scripts/filterbar/date-range-controller.js
app/scripts/filterbar/numeric-range-directive.js
app/scripts/custom-reports/custom-reports-modal-controller.js
app/scripts/custom-reports/module.js
app/scripts/custom-reports/custom-report-controller.js
app/scripts/custom-reports/table-data-string-directive.js
app/scripts/custom-reports/aggregations-config.js
app/scripts/toddow/module.js
app/scripts/toddow/toddow-directive.js
app/scripts/views/map/module.js
app/scripts/views/map/map-directive.js
app/scripts/views/map/layers-controller.js
app/scripts/views/map/map-controller.js
app/scripts/views/map/layers-directive.js
app/scripts/views/account/module.js
app/scripts/views/account/account-controller.js
app/scripts/views/duplicates/module.js
app/scripts/views/duplicates/resolve-duplicate-modal-controller.js
app/scripts/views/duplicates/duplicates-list-directive.js
app/scripts/views/duplicates/duplicates-list-controller.js
app/scripts/views/dashboard/module.js
app/scripts/views/dashboard/dashboard-controller.js
app/scripts/views/dashboard/dashboard-directive.js
app/scripts/views/login/auth-controller.js
app/scripts/views/login/module.js
app/scripts/views/record/embed-map-directive.js
app/scripts/views/record/embed-map-controller.js
app/scripts/views/record/module.js
app/scripts/views/record/list-directive.js
app/scripts/views/record/details-controller.js
app/scripts/views/record/details-directive.js
app/scripts/views/record/list-controller.js
app/scripts/views/record/add-edit-directive.js
app/scripts/views/record/add-edit-controller.js
app/scripts/views/record/details-modal-controller.js
app/scripts/recent-counts/module.js
app/scripts/recent-counts/recent-counts-directive.js
app/scripts/recent-counts/recent-counts-controller.js
app/scripts/social-costs/social-costs-directive.js
app/scripts/social-costs/module.js
app/scripts/social-costs/social-costs-controller.js
app/scripts/weather/weather-service.js
app/scripts/weather/module.js
app/scripts/weather/weather-label.js
app/scripts/stepwise/module.js
app/scripts/stepwise/stepwise-directive.js
app/scripts/map-layers/recent-events/module.js
app/scripts/map-layers/recent-events/recent-events-layer-directive.js
app/scripts/map-layers/module.js
app/scripts/map-layers/baselayers-service.js
app/scripts/map-layers/tile-url-service.js
app/scripts/details/details-reference-controller.js
app/scripts/details/details-image-directive.js
app/scripts/details/details-integer-directive.js
app/scripts/details/details-constants-directive.js
app/scripts/details/details-tabs-controller.js
app/scripts/details/details-single-directive.js
app/scripts/details/module.js
app/scripts/details/details-number-controller.js
app/scripts/details/details-integer-controller.js
app/scripts/details/details-multiple-controller.js
app/scripts/details/details-text-directive.js
app/scripts/details/details-number-directive.js
app/scripts/details/details-field-directive.js
app/scripts/details/details-tabs-directive.js
app/scripts/details/details-single-controller.js
app/scripts/details/details-selectlist-controller.js
app/scripts/details/details-reference-directive.js
app/scripts/details/details-selectlist-directive.js
app/scripts/details/details-multiple-directive.js
app/scripts/details/details-image-controller.js
app/scripts/details/details-text-controller.js
app/scripts/details/details-constants-controller.js
app/scripts/details/details-field-controller.js
app/scripts/saved-filters/saved-filter-as-html.js
app/scripts/saved-filters/module.js
app/scripts/saved-filters/saved-filters-controller.js
app/scripts/saved-filters/saved-filters-directive.js
app/scripts/saved-filters/saved-filters-modal-controller.js
app/scripts/audit/module.js
app/scripts/audit/audit-download-modal-controller.js
app/scripts/state/initialstate-service.js
app/scripts/state/boundarystate-service.js
app/scripts/state/geographystate-service.js
app/scripts/state/module.js
app/scripts/state/zoom-to-address-directive.js
app/scripts/state/recordschemastate-service.js
app/scripts/state/zoom-to-boundary-directive.js
app/scripts/state/mapstate-service.js
app/scripts/state/recordstate-service.js
app/scripts/state/filters-service.js
app/scripts/state/languagestate-service.js
app/scripts/navbar/module.js
app/scripts/navbar/navbar-directive.js
app/scripts/navbar/navbar-controller.js
app/scripts/resources/audit-logs-service.js
app/scripts/resources/assignments-service.js
app/scripts/resources/blackspots-service.js
app/scripts/resources/module.js
app/scripts/resources/boundaries-service.js
app/scripts/resources/query-builder-service.js
app/scripts/resources/saved-filters-service.js
app/scripts/resources/records-service.js
app/scripts/resources/recordexports-service.js
app/scripts/resources/duplicates-service.js
app/scripts/resources/aggregate-query-service.js
app/scripts/resources/polygons-service.js
app/scripts/leaflet/leaflet-map-directive.js
app/scripts/leaflet/module.js
app/scripts/leaflet/leaflet-defaults-provider.js
app/scripts/localization/date-picker-directive.js
app/scripts/localization/datetime-picker-directive.js
app/scripts/localization/module.js
app/scripts/localization/date-utils.js
app/scripts/black-spots/black-spots-directive.js
app/scripts/black-spots/module.js
app/scripts/black-spots/black-spots-controller.js
app/scripts/app.js
app/scripts/tools/charts/charts-directive.js
app/scripts/tools/charts/charts-controller.js
app/scripts/tools/charts/module.js
app/scripts/tools/interventions/module.js
app/scripts/tools/interventions/interventions-controller.js
app/scripts/tools/interventions/interventions-directive.js
app/scripts/tools/enforcers/enforcers-directive.js
app/scripts/tools/enforcers/module.js
app/scripts/tools/enforcers/enforcers-controller.js
app/scripts/tools/export/module.js
app/scripts/tools/export/export-controller.js
app/scripts/tools/export/export-directive.js
app/scripts/nominatim/nominatim-service.js
app/scripts/nominatim/module.js
app/scripts/enforcers/enforcer-assignments-controller.js
app/scripts/enforcers/enforcers-modal-controller.js
app/scripts/enforcers/module.js
app/scripts/enforcers/assignment-map-directive.js
app/scripts/enforcers/assignment-map-controller.js
app/scripts/config.js
